### ISSUE TITLE
Add animation to Toggle Bar

### ISSUE THREAD

**Issue by anfal17** [anfal17/fruits-website#1]
when the toggle bar is clicked there are no animations or transition effects please consider adding some animation to it ;)

**Comment by abitsalihu** [comment]
Hey @anfal17, can you be more specific on when which toggle bar is clicked? Would you like the animation to happen to the fruit itself when it changes or the toggle bar that changes the fruit?

**Comment by anfal17** [comment]
> Hey @anfal17, can you be more specific on when which toggle bar is clicked? Would you like the animation to happen to the fruit itself when it changes or the toggle bar that changes the fruit?

![image](https://user-images.githubusercontent.com/92685449/210291905-d7b1167e-ed9a-40d0-be7b-8c6fcd027c1f.png)
when we click on hamburger and a menu is displayed I referred to adding animation during this transition

**Comment by abitsalihu** [comment]
@anfal17, okay got it now. Please assign me to this issue. :)
